language: python

env:
  - CCACHE=/usr/bin/ccache

matrix:
  fast_finish: true
  include:
    - sudo: false
      script: ./mach test-tidy
      cache: false
    - sudo: 9000
      dist: trusty
      script: ./mach build -d --verbose
      cache:
        directories:
          - .cargo
          - .servo
          - $HOME/.ccache
      addons:
        apt:
          packages:
            - cmake
            - freeglut3-dev
            - gperf
            - libosmesa6-dev
            - python-virtualenv
            - xorg-dev
            - ccache

branches:
  only:
    - master
