[package]
name = "devtools"
version = "0.0.1"
authors = ["The Servo Project Developers"]

[lib]
name = "devtools"
path = "lib.rs"
crate-type = ["dylib"]

[dependencies.devtools_traits]
path = "../devtools_traits"
